version: 2.1

setup: true

orbs:
  split-config: bufferings/split-config@0.0.6

workflows:
  generate-config:
    jobs:
      - split-config/generate-config:
          find-config-regex: .*/\.circleci/config\.yml
